### ISSUE TITLE
Base language ID not conforming to expected format

### ISSUE THREAD

**Issue by jdwillemse** [LiamMartens/sanity-plugin-intl-input#11]
I'm not sure if I'm doing something wrong or if I misunderstand the documentation. When a document is created the base language document is not saved in the `i18n.document-id.lang` format.

In my case, the languages are `en` and `de`. Here is what happens when I create a new document:

```json
    {
      "__i18n_lang": "en",
      "__i18n_refs": [
        {
          "_key": "i18n.96bd217d-b62b-487a-a3af-99223521c25f.de",
          "lang": "de"
        }
      ],
      "_createdAt": "2020-08-06T10:06:33Z",
      "_id": "96bd217d-b62b-487a-a3af-99223521c25f",
      "_rev": "4j5Pa2Lqh5267RdnSWaJRV",
      "_type": "header"
    },
    {
      "__i18n_lang": "de",
      "_createdAt": "2020-08-06T10:06:45Z",
      "_id": "i18n.96bd217d-b62b-487a-a3af-99223521c25f.de",
      "_rev": "uCrG0WvJqT0LCQ9sKkjYK5",
      "_type": "header"
    }
```

The base language document correctly references the translation, but the translation does not refer back to the base. The base ID is not in the expected format so this query does not return all translations of the document
```
*[_id in path("i18n.document-id.*")]
```

Am I mistaken in my expectations of the structure or is something wrong?

**Comment by LiamMartens** [comment]
Yes the base language one is the only one not adheres to the format because it is the original document. The id format is only for translations
