### ISSUE TITLE
Menu button not displayed in Document List

### ISSUE THREAD

**Issue by debackerl** [LiamMartens/sanity-plugin-intl-input#15]
After selection of a document type in the "Content" panel, if that document type has i18n activated, the "burger" menu in the document list does not appear.

This is the menu where you can typically sort documents. Of course, since each "meta-document" is actually made of one document per translations, sorting those "meta-documents" is a problem. I think it makes sense to allow sorting on the base translation document.

Alternatively, to make it a bit more correct, we could have a menu, where you can choose the locale of your choice, so that documents list shows only the document in the translation of your choice by default (e.g. see list of documents in Spanish instead of English for Spanish editor). In that case, the sorting option will make more sense: you sort based on the selected locale.

What do you think ? :-)

**Comment by LiamMartens** [comment]
Hm - I will look into it. Need to check what the possibilities are with showing custom menu buttons etc..

**Comment by LiamMartens** [comment]
Fixed in v5.0.5
