### ISSUE TITLE
Translated documents cannot be deleted

### ISSUE THREAD

**Issue by DennisRosen** [LiamMartens/sanity-plugin-intl-input#16]
Since the base language document holds hard references to its translated counterparts, they are not allowed to be deleted. I suggest adding a configuration parameter for the reference field, with the options:

1. Current behavior with a hard reference
2. Weak reference by setting the _weak property to true. Optionally source this value from the schema type field definition.
3. Use no reference field at all, ie it is disabled

Right now I have worked around this by setting the fieldNames.references property to a string with a single space " ", which _seems_ to work (no field is set by sanity when publishing) but is obviously very hacky. It also results in an uncaught exception visible in the console when publishing a new translation, so I am not sure if it might break other things as well.

**Comment by LiamMartens** [comment]
I will pick this up

**Comment by LiamMartens** [comment]
@DennisRosen  I have published a beta version of the plugin adding a `referenceBehavior` setting, as detailed [here](https://github.com/LiamMartens/sanity-plugin-intl-input/blob/master/docs/important-configuration.md), I'll do a little bit more testing before moving it to latest, but you can already see if this fits all your needs.

When trying on an existing project - you can always use the maintenance tab to fix old refs.

**Comment by LiamMartens** [comment]
Released in 5.0.5
