### ISSUE TITLE
Installation instructions are unclear for new Sanity users

### ISSUE THREAD

**Issue by modmatrix** [LiamMartens/sanity-plugin-intl-input#19]
In /docs/installation.md, in step 3, it says "Implement the structure", and provides some JavaScript code.

However, as a new Sanity user, I don't know what file I should put this code in.

Perhaps this could be updated to be a little more explicit?

**Comment by LiamMartens** [comment]
Fair enough; I'll add some additional instructions. To help you out now - you can simply copy the below code to a file called `deskStructure.js` which should be located in the root of your Sanity project
```
import * as Structure from 'sanity-plugin-intl-input/lib/structure';

// default implementation by re-exporting
export const getDefaultDocumentNode = Structure.getDefaultDocumentNode;
export default Structure.default;
```

More info about the structure builder can be found [here](https://www.sanity.io/guides/getting-started-with-structure-builder)
