### ISSUE TITLE
"referenceBehavior" does not change the behavior of references 

### ISSUE THREAD

**Issue by jakubpodolski** [LiamMartens/sanity-plugin-intl-input#21]
Despite using the beta version of the plugin the behavior of the references in translated documents does not change. 

This is my current configuration of `intl-input.json` 
```
{
  "base": "no",
  "languages": [
    { "name": "no", "title": "Norsk" },
    { "name": "en-gb", "title": "English" }
  ],
  "referenceBehavior": "weak"
}

```
The reference is still set to hard (created a new document): 
![image](https://user-images.githubusercontent.com/38116079/104901278-7a259700-597d-11eb-895a-e49a698e903e.png)

But according to this https://github.com/LiamMartens/sanity-plugin-intl-input/issues/16#issuecomment-760206831 it should work 

I think that in the `getConfig` function, the settings are not updated with the configuration from the file: 

```
referenceBehavior: ReferenceBehavior.HARD
```
Maybe `referenceBehavior: cfg.referenceBehavior || ReferenceBehavior.HARD` will fix the issue?

**Comment by LiamMartens** [comment]
@jakubpodolski  :facepalm: yup - I updated the beta version with this change

**Comment by jakubpodolski** [comment]
@LiamMartens Thanks for a quick response! 
The updated version works as expected. Thanks!
