### ISSUE TITLE
How do I query this?

### ISSUE THREAD

**Issue by samosaboy** [LiamMartens/sanity-plugin-intl-input#27]
How do I actually pass a locale to the groq query to get the data in the proper locale?

**Comment by LiamMartens** [comment]
Yes, you can read about the ID structures [here](https://github.com/LiamMartens/sanity-plugin-intl-input/blob/master/docs/datastructure-intl-doc.md)

Basically - for any document ID you can build up the translated ID manually by using the following structure `i18n.{base-document-id}.{locale}`. This means for a document with ID `foo` the translated document in locale `fr-fr` would have the ID `i18n.foo.fr-fr`
