### ISSUE TITLE
Get base language from query

### ISSUE THREAD

**Issue by ehuelsda** [LiamMartens/sanity-plugin-intl-input#29]
So I am adding languages dynamically in my studio and fetching them with a groq query. This works perfectly.

I would however also like to fetch the base language using a query, as I've added a field to my singleton settings document referencing the language to use as base language. I tried using the same pattern as when fetching the language array, but unfortunately this is not working. Is this at all possible, and if not, are there any plans to add this feature?

**Comment by LiamMartens** [comment]
Hm interesting question. At the moment since the base language should be hardcoded in the i18n configuration this is not supported. Though since it is hardcoded; could you not fetch it by matching it with your i18n config?

**Comment by ehuelsda** [comment]
Thank you for getting back to me so quickly.
Unfortunately I'm still rather new to sanity and wasn't able to find a way to do that. If you can give me a more detailed suggestion how to go about it, that would be great. It is however just a nice to have, not must have :)
