### ISSUE TITLE
Querying localized documents via GraphQL

### ISSUE THREAD

**Issue by TimonVS** [LiamMartens/sanity-plugin-intl-input#3]
Thanks a bunch for this awesome plugin! 

I was trying to figure out how to query translated documents via GraphQL, I did figure it out but it wasn't immediately obvious so I'm documenting it here for other people who are looking for it.

To find all English localized pages:

```graphql
{
  allPage(where: {_id: {matches: "**__i18n_en"}}) {
    _id
    # ...
  }
}
```

Obviously the above query is not ideal, and I'm not sure how you would query just the default language since it doesn't have such an extension in the ID.
I was thinking that maybe the plugin could add a hidden input field to the document? I'm not sure if that's possible but that would make it immediately queryable via GraphQL.

**Comment by LiamMartens** [comment]
I have now added an additional configuration option to change the field name the plugin injects so you can change it from `__i18n_lang` to `lang` for example. When doing this you can include the field as a hidden string field in your own schema so GraphQL can consider it as part of your own schema.

I have added a short section in the README file for it

![image](https://user-images.githubusercontent.com/5265324/78988484-56e9d380-7b31-11ea-9a63-a0466da3c0ae.png)
