### ISSUE TITLE
Flags not displaying

### ISSUE THREAD

**Issue by conjecture-studio** [LiamMartens/sanity-plugin-intl-input#35]
Just noticed that the flags arnt displaying properly for the document-wide translations. See images. It instead shows the sanity S logo.

I checked another sanity install i had cloned from the sanity translation demo, and that has the same issue.

Not sure if its a bug or a problem my end. I know sanity made a lot of changes recently with respects their new UI framework. Perhaps that could have interfered with something?

I'm also not clear on where the flag icons come from anyway, so it's hard to diagnose what's going on. How are they sourced and served by your plugin? 

Anyway, thought I'd let you know so you can check and see if it's a problem your end. If not, and the issue is with me, I'd really appreciate a pointer on how to resolve it!

Cheers

![image](https://user-images.githubusercontent.com/5064093/115866770-0a1e2580-a432-11eb-9af2-6c165879218b.png)

![image](https://user-images.githubusercontent.com/5064093/115867188-ab0ce080-a432-11eb-920c-9c067440cd4b.png)

**Comment by ehuelsda** [comment]
I suspect the issue comes from https://www.countryflags.io/ being down. 

What about a rewrite using [react-country-flag](https://github.com/danalloway/react-country-flag)?

**Comment by LiamMartens** [comment]
@ehuelsda  interesting. I wonder why countryflags has disappeared. I will have a look at the react package

**Comment by LiamMartens** [comment]
@conjecture-studio is this fixed? Looks like countryflags is back online and I would prefer not to include an additional package just to keep the size down.
