### ISSUE TITLE
Cant query data if token is not added. Meaning CDN can't be used

### ISSUE THREAD

**Issue by emilpriverrc** [LiamMartens/sanity-plugin-intl-input#44]
Hi, 

Have a problem where we are not able to load data if not the token is added to the request. This means that the CDN is not used.

Clarify:
Token is used: Able to load all translations on all languages with no problems.
Token is not added to the request( ex in sanity client): Not able to load data if not the data is base data.

Anyone that have had or have the same behavior? If so how did you solve it?

**Comment by Axeldeblen** [comment]
Sound like your default `idStructure` value is set to the default `subpath` you might want to change it to `delimiter` if you want to query the data without the access tokens. see this ref - https://github.com/LiamMartens/sanity-plugin-intl-input/blob/master/docs/important-configuration.md

**Comment by LiamMartens** [comment]
Yep you need to set the `idStructure` to `delimiter`; `subpath` is default because it is easier to query.
