### ISSUE TITLE
Editor and Translations tab not visible

### ISSUE THREAD

**Issue by rxkevin** [LiamMartens/sanity-plugin-intl-input#50]
![Screenshot 2021-06-17 at 16 38 27](https://user-images.githubusercontent.com/72786689/122408507-1e425700-cf8b-11eb-8d22-f88e691e4357.jpg)

Maybe I missed something, but I went through the steps on [Installation Instructions ](https://github.com/LiamMartens/sanity-plugin-intl-input/blob/master/docs/installation.md) . Judging by the fact `en_US` is indicated in the bottom panel, as well as `Delete (Including translations)` and `Translation Maintenance` tab is present in the list, I assume I got the plugin working.
I also copy/pasted the configuration from [Document-wide translation](https://github.com/LiamMartens/sanity-plugin-intl-input/blob/master/docs/usage-intl-doc.md). So in general this is just a bare-bones setup, and I cannot see editor & translations tabs as in the example.

Could it be due to an unsupported sanity version?

```
"@sanity/base": "^2.11.2",
"@sanity/components": "^2.2.6",
"@sanity/core": "^2.11.0",
"@sanity/default-layout": "^2.11.2",
"@sanity/default-login": "^2.11.1",
"@sanity/desk-tool": "^2.11.2",
"@sanity/vision": "^2.11.2",
"sanity-plugin-intl-input": "^5.1.0",
```

**Comment by LiamMartens** [comment]
@rxkevin you setup the desk structure as well?

**Comment by rxkevin** [comment]
My apologies, I got it working I missed this part of code:
```
export const getDefaultDocumentNode = (props) => {
  if (props.schemaType === 'test') {
      return S.document().views(Structure.getDocumentNodeViewsForSchemaType(props.schemaType));
  }
  return S.document();
};
```

It looked odd that this function does not connect to anything in the structure builder.

**Comment by LiamMartens** [comment]
@rxkevin FYI https://www.sanity.io/docs/structure-builder-reference#97e44ce262c9 if you want to know the structure builder details behind it
