### ISSUE TITLE
Error importing Sanity Object Input Field

### ISSUE THREAD

**Issue by davidli3100** [LiamMartens/sanity-plugin-intl-input#56]
Starting Sanity after installing the plugin results in this error:

```
Error in ./node_modules/sanity-plugin-intl-input/lib/resolver (part:@sanity/form-builder/input-resolver)
Module not found: Error: Can't resolve '@sanity/form-builder/lib/inputs/ObjectInput/Field'
```

sanity: 2.12.0
sanity-plugin-intl-input: 5.2.0

This is solved by changing
`var Field = require('@sanity/form-builder/lib/inputs/ObjectInput/Field');` to `var Field = require('@sanity/form-builder/lib/inputs/ObjectInput/ObjectInputField');` in `/resolver/index.js`

**Comment by LiamMartens** [comment]
Hm looks like this was changed from @sanity/form-builder 2.11 -> 2.12 - will need to update -> bit annoying though, don't want to break everyone else

**Comment by PHCCorso** [comment]
I'm also having the same problem. I can't update my project's dependencies without having this fixed.

**Comment by SimeonGriggs** [comment]
This should be fixed in the latest release of the Studio, see above

https://github.com/sanity-io/sanity/releases/tag/v2.12.1
