### ISSUE TITLE
Is there RTL support?

### ISSUE THREAD

**Issue by tomasbal** [LiamMartens/sanity-plugin-intl-input#61]
I want to ask if there is RTL support for translations, and if yes how can I apply it?

Thanks

**Comment by LiamMartens** [comment]
@tomasbal not at this time - what would you expect from this? For the UI to adjust for RTL I assume?

**Comment by tomasbal** [comment]
Hey @LiamMartens, yes the UI should reflect the RTL approach. But this might be a Sanity problem because the Portable Text component accepts RTL based languages, but breaks the formatting.
