### ISSUE TITLE
Wrong flags for Arabic and Farsi

### ISSUE THREAD

**Issue by tomasbal** [LiamMartens/sanity-plugin-intl-input#62]
Hello,

The editor displays wrong flags for Arabic and Farsi:
![image](https://user-images.githubusercontent.com/19740178/124891384-3b41d700-dfd9-11eb-891d-a8ae921b0fba.png)

Kind regards,
Tomislav

**Comment by LiamMartens** [comment]
@tomasbal what language code have you configured? The language code is used to determine the country and subsequently get the flag (from https://www.countryflags.io)

**Comment by tomasbal** [comment]
Hi @LiamMartens, the languages I configured are the following:
```
export const languages = [
  { name: "en_GB", title: "English" },
  { name: "ar", title: "Arabic" },
  { name: "fa", title: "Farsi" },
];
```

But I saw that I'm using wrong names for the languages so I updated them with the following and it's working:
`export const languages = [
  { name: "en_GB", title: "English" },
  { name: "ae", title: "Arabic" },
  { name: "ir", title: "Farsi" },
];
`

Thanks for the helping, I'm closing the issue.
