### ISSUE TITLE
Object key forces underscore / snake case

### ISSUE THREAD

**Issue by nboliver** [LiamMartens/sanity-plugin-intl-input#64]
Curious what the rationale is behind forcing object language keys to use snake case?  
https://github.com/LiamMartens/sanity-plugin-intl-input/blob/7d18cce3571f043e20c12b45b98c72dea1a59eac/src/utils/makeObjectKey.ts 

We are mostly using document translation, except in one area where we have a settings document that doesn't need translating, but one of its text fields _does_. 

Gatsby / gatsby-plugin-react-i18next is being used on the front end, and all our language keys are hyphen-separated so that they match up with what we have set in the gatsby-plugin-react-i18next languages array. The values from that array are used to set the html language attribute, where a [valid language tag is hyphen-separated](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang#language_tag_syntax) 

Is there a specific reason to force snake case on object keys?

**Comment by LiamMartens** [comment]
Actually the function you are referencing is not in use. You can use hyphen separated language codes if you want.
