### ISSUE TITLE
configurable base language per document

### ISSUE THREAD

**Issue by frontshift** [LiamMartens/sanity-plugin-intl-input#66]
I am new to Sanity and this plugin, so forgive me if there is an obvious answer to this question.
I was wondering if there is a way for me to override the default language in each post.

E.g. one post might be written in Spanish first and translated to English at a later time, while other posts may be available in English only etc.

Ideally I would be able to add a new field to the Post schema that lets me select the default language, e.g. Spanish. In which case the Spanish title would appear in the Posts pane (possibly with a language flag, indicating the default language), as opposed to "Untitled"

Is this something that would be relatively easy to achieve natively without needing additional plugin support?

I guess alternatively I could also add a title for the English version, prefix it with something to indicate that the default language is missing, omit the Slug and then only query posts for the default language that have a slug.

![image](https://user-images.githubusercontent.com/1984261/126746827-c1d4c73c-03cc-4f50-9a98-d039cf8eaa3f.png)

**Comment by LiamMartens** [comment]
@frontshift this is actually already possible.
In your schema you usually define `i18n: true` but you can actually use the field to override default config; so you could do the following:
```
{
  i18n: {
    base: 'es-es'
  }
}
```

Feel free to re-open if that doesn't cut it

**Comment by KuulArt** [comment]
@LiamMartens  - what you are talking about is to set base language per schema, right?
I think OP is talking about setting base language per document. So that you could create new documents in other locales that are not base. I am currently trying to achieve a similar thing and I'm stuck here.
