### ISSUE TITLE
Add reference to translated documents

### ISSUE THREAD

**Issue by jdwillemse** [LiamMartens/sanity-plugin-intl-input#7]
I have a feature request.

Would it be possible to link from a document to all of it's translated counterparts? This would mean that one can query a doc and its translations more easily. For my use case, it is quite common that a web page would have a language switch on every translated page. This link would be easier to create if there was an explicit link between the translations.

I'm using slugs as the key for querying for documents. This then means I have to do a second query once I have the ID from the slug to find the relevant translated document.

If I'm making this more difficult than it needs to be and there is a simple solution that I'm missing I'd love to hear about it 😃

**Comment by jdwillemse** [comment]
I was helped in the [sanity forums](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1594818125188100) with this solution:
```
"translated": *[(_id > ^._id && _id < ^._id + "a") || (^._id > _id && ^._id < _id + "a")]
```
I still think an explicit reference between documents would be a nice feature if it is possible.

**Comment by LiamMartens** [comment]
@jdwillemse  I have a working sample which would result in a structure as follows
```
{
  __i18n_refs: {
    nl_nl: {
      _type: "reference",
      _ref: "id"
    },
    en_us: {
      _type: "reference",
      _ref: "id"
    }
  }
}
```

Which then would be queryable as follows:
```
*[_id == "basedoc"] {
  __i18n_refs {
    nl_nl->{...}
    en_us->{...}
  }
}
```

Would this be sufficient?

**Comment by LiamMartens** [comment]
@jdwillemse  I will most likely change this to an array of references because this is simpler for GraphQL support.

**Comment by LiamMartens** [comment]
@jdwillemse I just published V5 which contains this feature.
V5 does contain a breaking change, you can check the migration guide :+1: 

The array of references looks like this
```
{
  __i18n_refs: [
    {
      lang: "lang_CULT",
      ref: {
        _type: "reference",
        _ref: "id"
      }
    }
  ]
}

```


allows you to do the following in a query
```
*[_type == "doctype"] {
  __i18n_refs[lang == "lang_CULT"] {
    lang,
    ref->{...}
  }
}
```

**Comment by jdwillemse** [comment]
This is awesome. Will upgrade and test it out asap
