### ISSUE TITLE
I wrote up a guide on using this plugin

### ISSUE THREAD

**Issue by nilsnh** [LiamMartens/sanity-plugin-intl-input#70]
Hi there. 👋  Thank you very much for building this plugin.

I just wanted to let you know that I wrote up a guide on this plugin which covers some of the gotchas that I encountered. (Most of it caused by me not properly reading the documentation.) You could perhaps link to this guide in your readme if you find it useful? If not that's totally fine as well. My guide: https://nilsnh.no/2021/08/22/guide-localizing-sanity-cms-with-the-intl-input-plugin/ 

Feel free to close this issue. 🙇

**Comment by LiamMartens** [comment]
@nilsnh that's awesome - I will include it in the README :pray:
