### ISSUE TITLE
the base language doesn't have __i18n_lang and __i18n_refs 

### ISSUE THREAD

**Issue by kimvuVarner** [LiamMartens/sanity-plugin-intl-input#78]
Hi, I'm struggeling to create a english document with norwegian and swedish translation. The english is the base but doesnt have the lang and ref attributes.

this could be related to this issue: https://github.com/sanity-io/sanity-plugin-content-calendar/issues/20 which happened after installing sanity-io/sanity-plugin-content-calendar. It may have interfered with the functionality of this plugin. Reading on some issues here, it seems to be related to custom publish action (ref comment: https://github.com/LiamMartens/sanity-plugin-intl-input/issues/60#issuecomment-883756409) which i think the sanity-io/sanity-plugin-content-calendar creates

querying: *[_id match "*b4d654f7-2b47-4339-9a92-d9ad5d111b43*"] gives:

![image](https://user-images.githubusercontent.com/89914537/134663806-4f1a3b69-bd25-4eda-86d3-e34d5632a03f.png)
where the first document should've had the __i18n_lang and __i18n_refs attributes

and my configfile intl-input.json looks like this:
{
    "idStructure": "subpath",
    "referenceBehavior": "hard",
    "languages": [
        { "name": "en", "title": "English (UK)" },
        { "name": "no", "title": "Norwegian" },
        { "name": "se", "title": "Swedish" }
      ]
}

**Comment by LiamMartens** [comment]
Yea it's probably also related to #60 
It's hard when you have multiple custom publish actions -- I did publish a beta version yesterday which exposes a utility to handle the same functionality of the intl plugin for your own custom publish actions; perhaps that could help? (you'll need `5.3.0-beta.1`)

Read:
https://github.com/LiamMartens/sanity-plugin-intl-input/blob/develop/docs/usage-with-custom-publish.md

**Comment by kimvuVarner** [comment]
Another thing: in https://github.com/sanity-io/sanity-plugin-content-calendar/issues/20 the delete and duplicate actions from this plugin gets overwritten by  sanity-plugin-content-calendar. Is it possible to have them back as well? are they also exposed as utilities too?

**Comment by LiamMartens** [comment]
@kimvuVarner I have published a new beta version which exports those actions as well;
```
import {
  PublishWithi18nAction,
  DeleteWithi18nAction,
  DuplicateWithi18nAction
} from 'sanity-plugin-intl-input/lib/actions';
```

**Comment by kimvuVarner** [comment]
Sweet!, thank you
