### ISSUE TITLE
Add cheat sheet documentation

### ISSUE THREAD

**Issue by gpoole** [LiamMartens/sanity-plugin-intl-input#89]
I think it would be helpful to have a cheatsheet/recipe list similar to the [GROQ cheat sheet Sanity have on their site](https://www.sanity.io/docs/query-cheat-sheet). I think it helps with learning the structure of the plugin and saves users having to figure out some best practice stuff for themselves. There's some helpful examples throughout the docs, but I think having a list of common queries would be helpful and also maybe encourage users to submit their own.

Here's some examples of ones I've found useful (please correct me if I've done anything the wrong way!)

Querying for base language documents only:

```groq
*[_type == "type" && !(_id in path("drafts.i18n.*") && _id in path("i18n.**"))]
```

Looking up documents in a specific language:

```groq
*[_type == "type" && __i18n_lang == $lang]
```

Getting a list of all translations available for a given document type:

```groq
*[_type == "type" && !(_id in path("drafts.i18n.*") && _id in path("i18n.**"))] {
  "languages": [__i18n_lang, ...__i18n_refs[].lang]
}
```

Looking up a property on a base language document (I hide the slug field on my translations because I want all my slugs in base language):

```groq
*[_type == "type" && __i18n_lang == $lang] {
  "slug": select(
    // For translations, look up the slug on the base language document, not this document
    _id in path("i18n.**") => *["i18n." + _id + "." + ^.__i18n_lang == ^._id][0].slug.current,
    slug.current
  )
}
```

Happy to bundle these up into a PR if it's useful?

**Comment by LiamMartens** [comment]
@gpoole Added some; feel free to PR any additionals you want to include ([see here](https://github.com/LiamMartens/sanity-plugin-intl-input/blob/develop/docs/groq-cheatsheet.md)

**Comment by gpoole** [comment]
Looks good, thanks @LiamMartens
