### ISSUE TITLE
Add a heads up about using subPath in docs

### ISSUE THREAD

**Issue by ehuelsda** [LiamMartens/sanity-plugin-intl-input#93]
Can I suggest adding a little heads up in the docs about the need to be authenticated to be able to fetch localized documents if using subPath in the id structure? People keep posting questions about this in the Sanity Slack channel and that shouldn't really be necessary.

**Comment by ehuelsda** [comment]
I know, but it seems not to be visible enough 🤷 Would be cool if you put it in the main README.

**Comment by jaronheard** [comment]
Adding another voice for including a larger disclaimer in the main README. It's not intuitive that you would need to be authenticated just to read documents based on Sanity's access model, and it was a difficult issue to debug. It's likely if it was in the main README I would have saved multiple hours, and it sounds like if people are asking about it in the Sanity Slack repeatedly that I'm not the only one.

(I'm really grateful for this project, thank you!! 💖)
