### ISSUE TITLE
using AppolloClient from nextJS gives only en translations, using GraphQL

### ISSUE THREAD

**Issue by kimvuVarner** [LiamMartens/sanity-plugin-intl-input#97]
I don't really know if this is an issue directly related to this plugin, but when using a GraphQL from my nextjs app to query sanity I only get the english translation:

The funny thing is that the deployed api which is the same URI i use for the ApolloClient, does actually have all the languages uri is(`https://<sanity-id>.api.sanity.io/v1/graphql/test/default`) as you can see theres no, en and sv here:
![image](https://user-images.githubusercontent.com/89914537/140952605-19d0a326-441f-4be3-85b9-7fe71b887cbb.png)
Heres the exact same query using apolloClient (only have en):
![image](https://user-images.githubusercontent.com/89914537/140952669-33739a08-9d70-45bd-8244-97260210c9ed.png)

my createApolloClient:
![image](https://user-images.githubusercontent.com/89914537/140953824-2f4898f7-901d-479e-8ede-ea127c843271.png)

**Comment by LiahMartens** [comment]
@kimvuVarner this is due to the ID structure of the translations. By default it will use a subpath (like drafts: `i18n.base-id.lang-culture`). However any documents using a path structure are private which means you need an access token to query them.
